"This code finds the factorial of the provided number.
"0! =1 , 1!=1 , 5!=5*4*3*2*1

DATA: FACTORIAL_RESULT TYPE I.
PARAMETERS: NUMBER TYPE I.
WRITE: / 'The input is' , NUMBER.
PERFORM FACTORIAL USING NUMBER 
CHANGING FACTORIAL_RESULT.
WRITE: / 'The result is' , FACTORIAL_RESULT.

FORM FACTORIAL USING FNUMBER
CHANGING FOUTPUT.
" 0! = 1
IF FNUMBER = 0.
 FOUTPUT = 1.
ENDIF.
"1! = 1
IF FNUMBER = 1.
FOUTPUT = 1.
ENDIF.
FOUTPUT = FNUMBER.
WHILE FNUMBER > 1.
FNUMBER = FNUMBER - 1.
FOUTPUT = FOUTPUT * FNUMBER.
ENDWHILE.
ENDFORM.
